In [9]:
import pandas as pd

In [10]:
df=pd.read_csv("trait anxiety score4.csv")

In [11]:
df

,Timestamp,Email address,Name,I feel fine,I tire quickly,I feel like crying,I wish I could be as happy as others seem to be,I am losing opportunities because I cannot make decisions fast,I feel rested,I am calm,...,I am inclined to take things hard,I lack self-confidence,I feel secure,I try to avoid facing a crisis or difficulty,I feel blue,I am content,Some unimportant thoughts run through my mind and bother me,I take disappointments so keenly that I cannot get them out of my mind,I am a steady person,I become tense and upset when I think about my current concerns
0,10/04/2024 14:49:07,NaN,Mayankit,3,3,1,3,3,2,3,...,3,4,3,3,3,3,4,4,3,3
1,10/04/2024 16:13:21,NaN,Ajitesh Shree,4,2,1,2,4,2,1,...,4,4,2,3,1,2,3,4,2,3
2,10/04/2024 17:43:17,NaN,Bhavishya Prakash Singh,4,1,1,1,1,4,4,...,1,1,4,1,2,4,1,1,4,1
3,10/04/2024 21:58:30,NaN,Nandini Goel,3,2,2,1,1,3,3,...,3,1,3,3,1,3,2,2,3,2
4,10/04/2024 22:02:12,NaN,Anshul Jain,4,1,1,1,1,4,4,...,1,1,4,4,1,4,1,1,2,1
5,10/04/2024 22:05:00,NaN,Sanmati Pande,4,2,3,2,1,2,3,...,3,1,4,3,1,4,4,3,4,3
6,10/04/2024 22:20:08,NaN,Chhavi,3,3,3,4,1,4,3,...,3,2,3,3,2,3,4,2,3,3
7,11/04/2024 16:44:50,NaN,Ashi Vijayvargiya,3,2,1,3,1,4,3,...,3,1,4,3,1,4,3,2,2,3
8,11/04/2024 16:47:52,NaN,Bhanupratap,4,2,1,4,1,3,4,...,3,1,4,1,1,3,1,1,3,1
9,11/04/2024 16:48:30,NaN,Huzaif,3,2,1,3,2,3,3,...,3,2,4,3,2,2,3,3,2,2
10,11/04/2024 16:51:51,NaN,Sameer Verma,3,3,4,1,2,2,3,...,1,4,1,2,3,3,2,2,2,3
11,11/04/2024 16:53:39,NaN,Abhishek Kumar,3,2,2,2,2,1,2,...,2,2,3,2,2,3,3,2,3,2
12,11/04/2024 16:54:49,NaN,Rohit Raj,3,1,2,1,4,2,4,...,3,1,3,2,1,1,2,1,4,4
13,11/04/2024 16:59:47,NaN,Ruchit,2,4,2,4,4,3,3,...,1,3,3,4,3,2,4,2,3,3
14,11/04/2024 17:09:15,NaN,Prashant,4,2,2,4,3,3,4,...,4,2,2,1,2,4,2,2,4,2

In [12]:
df.sort_values('Name',inplace=True)

In [13]:
df

,Timestamp,Email address,Name,I feel fine,I tire quickly,I feel like crying,I wish I could be as happy as others seem to be,I am losing opportunities because I cannot make decisions fast,I feel rested,I am calm,...,I am inclined to take things hard,I lack self-confidence,I feel secure,I try to avoid facing a crisis or difficulty,I feel blue,I am content,Some unimportant thoughts run through my mind and bother me,I take disappointments so keenly that I cannot get them out of my mind,I am a steady person,I become tense and upset when I think about my current concerns
11,11/04/2024 16:53:39,NaN,Abhishek Kumar,3,2,2,2,2,1,2,...,2,2,3,2,2,3,3,2,3,2
1,10/04/2024 16:13:21,NaN,Ajitesh Shree,4,2,1,2,4,2,1,...,4,4,2,3,1,2,3,4,2,3
4,10/04/2024 22:02:12,NaN,Anshul Jain,4,1,1,1,1,4,4,...,1,1,4,4,1,4,1,1,2,1
7,11/04/2024 16:44:50,NaN,Ashi Vijayvargiya,3,2,1,3,1,4,3,...,3,1,4,3,1,4,3,2,2,3
8,11/04/2024 16:47:52,NaN,Bhanupratap,4,2,1,4,1,3,4,...,3,1,4,1,1,3,1,1,3,1
2,10/04/2024 17:43:17,NaN,Bhavishya Prakash Singh,4,1,1,1,1,4,4,...,1,1,4,1,2,4,1,1,4,1
6,10/04/2024 22:20:08,NaN,Chhavi,3,3,3,4,1,4,3,...,3,2,3,3,2,3,4,2,3,3
9,11/04/2024 16:48:30,NaN,Huzaif,3,2,1,3,2,3,3,...,3,2,4,3,2,2,3,3,2,2
0,10/04/2024 14:49:07,NaN,Mayankit,3,3,1,3,3,2,3,...,3,4,3,3,3,3,4,4,3,3
3,10/04/2024 21:58:30,NaN,Nandini Goel,3,2,2,1,1,3,3,...,3,1,3,3,1,3,2,2,3,2
14,11/04/2024 17:09:15,NaN,Prashant,4,2,2,4,3,3,4,...,4,2,2,1,2,4,2,2,4,2
12,11/04/2024 16:54:49,NaN,Rohit Raj,3,1,2,1,4,2,4,...,3,1,3,2,1,1,2,1,4,4
13,11/04/2024 16:59:47,NaN,Ruchit,2,4,2,4,4,3,3,...,1,3,3,4,3,2,4,2,3,3
10,11/04/2024 16:51:51,NaN,Sameer Verma,3,3,4,1,2,2,3,...,1,4,1,2,3,3,2,2,2,3
5,10/04/2024 22:05:00,NaN,Sanmati Pande,4,2,3,2,1,2,3,...,3,1,4,3,1,4,4,3,4,3

In [14]:
df.to_csv("trait.csv",index=None)